Repository eggjs/egg, pull requests merged in 2018-04, with the labels that each got.

#2283 feat: support customized client error
  config/config.default.js
  index.d.ts
  lib/application.js
  test/fixtures/apps/app-server-customized-client-error/app.js
  test/fixtures/apps/app-server-customized-client-error/app/router.js
  test/fixtures/apps/app-server-customized-client-error/config/config.default.js
  test/fixtures/apps/app-server-customized-client-error/package.json
  test/lib/cluster/app_worker.test.js
  test/lib/core/httpclient.test.js
Labels: core: application

#2373 docs(controller): add ctx.redirect
  docs/source/en/basics/controller.md
  docs/source/zh-cn/basics/controller.md
Labels: type: document

#2375 docs: intro session.renew in the doc
  docs/source/en/core/cookie-and-session.md
  docs/source/zh-cn/core/cookie-and-session.md
Labels: type: document

#2235 EN translation for passport tutorial
  docs/source/en/tutorials/passport.md
  docs/source/zh-cn/tutorials/passport.md
Labels: type: document

#2392 docs(plugin): add singleton support async create function
  docs/source/en/advanced/plugin.md
  docs/source/zh-cn/advanced/plugin.md
Labels: type: document

#2407 Release 1.13.2
  History.md
  package.json
Labels: type: release

#2406 Release 2.7.0
  History.md
  package.json
Labels: type: release

#2417 Release 2.7.1
  History.md
  package.json
Labels: type: release
