Repository eggjs/egg, pull requests merged in 2018-10, with the labels that each got.

#3058 feat: add Subscription base class on app instance
  lib/egg.js
  test/fixtures/apps/schedule/app/schedule/hello.js
  test/fixtures/apps/schedule/app/schedule/sub/cron.js
  test/lib/plugins/schedule.test.js
Labels: plugin: egg-schedule

#3076 Release 1.16.2
  History.md
  package.json
Labels: type: release

#3075 Release 2.12.0
  History.md
  package.json
Labels: type: release

#3118 fix: runInBackground should emit error event
  app/extend/context.js
  test/app/extend/context.test.js
Labels: benchmark, type: feature
