Repository eggjs/egg, pull requests merged in 2018-03, with the labels that each got.

#2150 Release 2.4.0
  History.md
  package.json
Labels: type: release

#2156 fix: try to use custom function name first
  app/extend/context.js
  test/app/extend/context.test.js
  test/fixtures/apps/ctx-background/app/controller/custom.js
  test/fixtures/apps/ctx-background/app/router.js
Labels: core: context

#2161 fix: try to use custom function name first
  app/extend/context.js
  test/app/extend/context.test.js
  test/fixtures/apps/ctx-background/app/controller/custom.js
  test/fixtures/apps/ctx-background/app/router.js
Labels: core: context

#2160 Release 1.13.1
  History.md
  package.json
Labels: type: release

#2164 Release 2.4.1
  History.md
  package.json
Labels: type: release

#2230 feat: display router when log app
  lib/egg.js
Labels: core: application

#2270 docs: deprecate ignoreJSON
  docs/source/en/core/security.md
  docs/source/zh-cn/core/security.md
Labels: type: document

#2274 docs(security): add ssrf in security
  docs/source/en/core/security.md
  docs/source/zh-cn/core/security.md
Labels: type: document

#2238 EN translation for resources doc
  docs/source/en/resource.md
Labels: type: document

#2239 EN translation for style guide doc
  docs/source/en/style-guide.md
Labels: type: document

#2240 EN translation for view plugin dev doc
  docs/source/en/advanced/view-plugin.md
Labels: type: document

#2220 docs: add assets document
  docs/source/_data/guide_toc.yml
  docs/source/en/tutorials/assets.md
  docs/source/languages/en.yml
  docs/source/languages/th.yml
  docs/source/languages/zh-cn.yml
  docs/source/zh-cn/tutorials/assets.md
Labels: type: document
