Repository eggjs/egg, pull requests merged in 2019-02, with the labels that each got.

#3430 feat: support single process mode
  index.js
  lib/core/messenger/index.js
  lib/core/messenger/ipc.js
  lib/core/messenger/local.js
  lib/egg.js
  lib/start.js
  package.json
  test/fixtures/apps/demo/index.js
  test/index.test.js
  test/lib/cluster/cluster-client.test.js
  test/lib/core/messenger/ipc.test.js
  test/lib/core/messenger/local.test.js
  test/lib/start.test.js
  test/utils.js
Labels: cluster-client, semver: minor

#3443 Release 2.15.0
  History.md
  package.json
Labels: type: release

#3460 feat: allow ctx.router setter
  app/extend/context.js
  test/app/extend/context.test.js
  test/fixtures/apps/context-config-app/app/controller/home.js
Labels: core: context

#3461 Release 2.16.0
  History.md
  package.json
Labels: type: release

#3469 Release 2.16.1
  History.md
  package.json
Labels: semver: patch, type: release

#3474 Release 2.16.2
  History.md
  package.json
Labels: type: release

#3481 Release 2.17.0
  History.md
  package.json
Labels: type: release

#3498 Release 2.18.0
  History.md
  package.json
Labels: type: release
