Repository eggjs/egg, pull requests merged in 2019-10, with the labels that each got.

#3903 feat: set default body-parser limitation to 1mb
  config/config.default.js
  test/app/middleware/body_parser.test.js
  test/fixtures/apps/body_parser_testapp/config/config.default.js
Labels: Inactive

#3905 feat:Singleton returns client name when create client
  lib/core/singleton.js
  test/lib/core/singleton.test.js
Labels: Inactive

#4014 feat: support config.maxIpsCount
  app/extend/request.js
  config/config.default.js
  docs/source/en/tutorials/proxy.md
  docs/source/zh-cn/tutorials/proxy.md
  test/app/extend/request.test.js
Labels: type: feature

#4013 feat: support config.maxIpsCount
  .github/workflows/ci.yml
  .travis.yml
  app/extend/request.js
  config/config.default.js
  test/app/extend/request.test.js
  test/lib/core/httpclient.test.js
Labels: type: feature

#4017 Release 1.20.0
  History.md
  package.json
Labels: type: release

#4015 Release 2.25.0
  History.md
  package.json
Labels: type: release
