Repository eggjs/egg, pull requests merged in 2019-04, with the labels that each got.

#3607 Release 1.18.0
  History.md
  package.json
Labels: semver: minor, type: release

#3617 Release 2.21.0
  History.md
  package.json
Labels: type: release

#3616 Release 1.19.0
  History.md
  package.json
Labels: type: release

#3623 Release 2.21.1
  History.md
  package.json
Labels: type: release

#3632 Release 2.22.0
  History.md
  package.json
Labels: semver: minor, type: release

#3660 Release 2.22.1
  History.md
  package.json
Labels: semver: patch

#3666 Release 2.22.2
  History.md
  package.json
Labels: semver: patch, type: release
