Repository eggjs/egg, pull requests merged in 2022-09, with the labels that each got.

#5023 feat: update egg-multipart 2.x -> 3.x
  .gitignore
  lib/agent.js
  lib/application.js
  lib/core/messenger/ipc.js
  lib/core/messenger/local.js
  lib/egg.js
  package.json
  scripts/jsdoc.js
  test/fixtures/apps/app-ts/app/controller/foo.ts
  test/fixtures/apps/app-ts/tsconfig.json
  test/lib/egg.test.js
Labels: type: feature, plugin: egg-multipart

#5027 feat(graceful): support ignoreCode
  lib/application.js
  package.json
  test/fixtures/apps/app-die-ignore-code/app/router.js
  test/fixtures/apps/app-die-ignore-code/config/config.default.js
  test/fixtures/apps/app-die-ignore-code/package.json
  test/lib/cluster/master.test.js
Labels: type: feature, cluster-client

#5028 Release 3.3.0
  History.md
  package.json
Labels: semver: minor, type: release

#5032 fix: fallback egg-multipart to v2
  package.json
Labels: type: bug, plugin: egg-multipart

#5033 Release 3.3.1
  History.md
  package.json
Labels: semver: patch, type: release

#5037 🐛 FIX: Allow override HttpClientNext
  lib/egg.js
  test/fixtures/apps/httpclient-next-overwrite/app.js
  test/fixtures/apps/httpclient-next-overwrite/config/config.default.js
  test/fixtures/apps/httpclient-next-overwrite/package.json
  test/lib/core/httpclient.test.js
Labels: type: bug, core: httpclient

#5038 Release 3.3.3
  History.md
  package.json
Labels: semver: patch
