Repository eggjs/egg, pull requests merged in 2022-12, with the labels that each got.

#5076 chore: use actions to deploy vercel project
  .github/workflows/vercel-preview.yml
  .github/workflows/vercel-production.yml
  .gitignore
  vercel.json
Labels: type: document

#5079 📦 NEW: Add ctxStorage and currentContext d.ts
  index.d.ts
  package.json
Labels: typescript

#5081 Release 3.6.0
  History.md
Labels: semver: minor

#5066 📖 DOC: Use @eggjs/tsconfig for tsconfig.json
  site/docs/tutorials/typescript.md
  site/docs/tutorials/typescript.zh-CN.md
Labels: type: document

#5086 Release 3.7.0
  History.md
  package.json
Labels: semver: minor, type: release

#5089 Release 3.8.0
  History.md
  package.json
Labels: semver: minor, type: release, plugin: egg-schedule

#5094 📦 NEW: Run async function in the anonymous context scope
  index.d.ts
  lib/application.js
  test/app/extend/application.test.js
  test/fixtures/apps/app-runInAnonymousContextScope/app.js
  test/fixtures/apps/app-runInAnonymousContextScope/config/config.default.js
  test/fixtures/apps/app-runInAnonymousContextScope/config/config.unittest.js
  test/fixtures/apps/app-runInAnonymousContextScope/package.json
  test/fixtures/apps/app-ts-type-check/normal.ts
Labels: core: context, core: application

#5092 👌 IMPROVE: Keep more compatible d.ts on httpclient request
  index.d.ts
  package.json
  test/app/middleware/meta.test.js
  test/fixtures/apps/app-ts/app/controller/foo.ts
  test/fixtures/apps/app-ts/config/config.ts
Labels: core: httpclient, typescript

#5100 Release 3.9.0
  History.md
  package.json
  test/fixtures/apps/app-ts-type-check/normal.ts
Labels: semver: minor, type: release

#5101 🐛 FIX: Should import types from urllib-next root path
  .github/workflows/release.yml
  index.d.ts
  package.json
  test/fixtures/apps/app-ts/app/controller/foo.ts
Labels: core: urllib

#5107 fix: fix currentContext typo
  index.d.ts
  test/fixtures/apps/app-ts/app/controller/foo.ts
Labels: type: bug
