Repository eggjs/egg, pull requests merged in 2023-01, with the labels that each got.

#4965 docs: Typo fix
  site/docs/tutorials/sequelize.md
Labels: Inactive

#4687 fix: add ssrf declaration
  index.d.ts
Labels: Inactive

#5113 fix: remove duplicate identifier ssrf
  index.d.ts
  index.test-d.ts
  package.json
Labels: type: bug

#5114 feat: siteFile favicon config support function type
  app/middleware/site_file.js
  test/app/middleware/site_file.test.js
  test/fixtures/apps/favicon-function/app/controller/home.js
  test/fixtures/apps/favicon-function/app/router.js
  test/fixtures/apps/favicon-function/config/config.default.js
  test/fixtures/apps/favicon-function/package.json
Labels: type: feature

#5127 feat: export urllib types
  .github/workflows/nodejs.yml
  index.d.ts
  package.json
  test/app/extend/request.test.js
  test/fixtures/apps/app-ts-type-check/normal.ts
Labels: core: httpclient

#5132 fix(types): app.router.url params should be optional
  index.d.ts
  test/fixtures/apps/app-ts/app/controller/foo.ts
Labels: core: router
