Repository eggjs/egg, pull requests merged in 2023-06, with the labels that each got.

#5199 test: fix getting "httpClient" instance before "app" is ready
  test/fixtures/apps/httpclient-tracer/app.js
  test/lib/core/httpclient.test.js
Labels: type: test

#5200 test: fix and enable 'egg.test.js'
  test/fixtures/apps/demo/app.js
  test/lib/egg.test.js
Labels: type: test

#5203 test: remove useless "async" support check
  test/async/index.test.js
  test/asyncSupport.test.js
Labels: type: test

#5204 chore: fix "Continous Integrations" sync badge state
  README.md
  README.zh-CN.md
Labels: type: document

#5210 fix: ipc not work with worker_threads mode
  lib/core/messenger/ipc.js
  package.json
  test/lib/core/messenger/ipc.test.js
Labels: type: bug

#5211 test: make plugins/development test stable
  .github/workflows/codeql-analysis.yml
  .github/workflows/nodejs.yml
  .github/workflows/release.yml
  test/lib/plugins/development.test.js
Labels: type: test

#5216 feat: add getSingletonInstance alias to singleton.get(id)
  lib/core/singleton.js
  test/lib/core/singleton.test.js
Labels: core

#5221 doc: remove useless "*.jsdoc"
  lib/jsdoc/context.jsdoc
  lib/jsdoc/request.jsdoc
  lib/jsdoc/response.jsdoc
Labels: type: document

#5217 fix: compatible with content-type extra semicolon
  package.json
  test/app/middleware/body_parser.test.js
Labels: type: bug, core: bodyparser

#5224 doc: add missing links for menu items
  site/docs/advanced/index.md
  site/docs/advanced/index.zh-CN.md
  site/docs/basics/index.md
  site/docs/basics/index.zh-CN.md
  site/docs/core/index.md
  site/docs/core/index.zh-CN.md
Labels: type: document

#5225 doc: fix links
  site/docs/advanced/index.md
  site/docs/advanced/index.zh-CN.md
  site/docs/basics/index.md
  site/docs/basics/index.zh-CN.md
  site/docs/basics/middleware.md
  site/docs/basics/middleware.zh-CN.md
  site/docs/core/index.md
  site/docs/core/index.zh-CN.md
Labels: type: document

#5227 docs: Official maintained ORM model is egg-orm
  site/docs/tutorials/index.md
  site/docs/tutorials/index.zh-CN.md
Labels: type: document

#5228 fix: don't require inspector module on production env
  lib/egg.js
Labels: type: bug

#5232 fix: add missing args definition on runSchedule
  index.d.ts
Labels: typescript
